#!/bin/sh

userresources=$HOME/etc/X11/xresources
usermodmap=$HOME/etc/X11/modmap

sysresources=/etc/X11/xinit/Xresources
sysmodmap=/etc/X11/xinit/Xmodmap

composite=$XDG_CONFIG_HOME/X11/compton.conf

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ -f "$composite" ]; then
	compton -b --config "$composite"
fi

xsetroot -cursor_name left_ptr

xset +fp /usr/share/fonts/jmk
xset fp rehash

setxkbmap de_crshd
xset r rate 190 40

(
	while true; do
		wallpaper
		sleep 600
	done
&)

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/* ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# exec xmonad
exec sawfish
