# The following lines were added by compinstall

zstyle ':completion:*' completer _expand _complete _ignored _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle :compinstall filename '/home/crshd/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/var/zsh/histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd extendedglob
# End of lines configured by zsh-newuser-install

for r in $HOME/etc/zsh/*.zsh; do
	if [[ $DEBUG > 0 ]]; then
		echo "zsh: sourcing $r"
	fi
	source $r
done

if [ -f $HOME/etc/dircolors/dircolors ]; then
	eval $(dircolors -b $HOME/etc/dircolors/dircolors)
fi
